"""sprint5 plan import comparison analysis

Revision ID: c5515536b1c3
Revises: a1f4c9d2e7b1
Create Date: 2026-07-09 05:56:21.445311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5515536b1c3'
down_revision: Union[str, Sequence[str], None] = 'a1f4c9d2e7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('applied_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_plans_user_id'), 'imported_plans', ['user_id'], unique=False)
    op.create_index('ix_imported_plans_user_type', 'imported_plans', ['user_id', 'plan_type'], unique=False)
    op.create_table('plan_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('imported_plan_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('effectiveness_score', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_plan_id'], ['imported_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_analyses_imported_plan_id'), 'plan_analyses', ['imported_plan_id'], unique=False)
    op.create_index(op.f('ix_plan_analyses_user_id'), 'plan_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_analyses_user_id'), table_name='plan_analyses')
    op.drop_index(op.f('ix_plan_analyses_imported_plan_id'), table_name='plan_analyses')
    op.drop_table('plan_analyses')
    op.drop_index('ix_imported_plans_user_type', table_name='imported_plans')
    op.drop_index(op.f('ix_imported_plans_user_id'), table_name='imported_plans')
    op.drop_table('imported_plans')
    # ### end Alembic commands ###
